### ISSUE TITLE
Time management and faster than real-time simulation

### ISSUE THREAD

**Issue by adegroote** [morse-simulator/morse#388]
Need to better understand how time works in Blender / Morse, and expose it properly.

Make more clear mode concerning time (proposed by Charles):
   - best-effort real-time (i.e drop frame if needed)
   - simulated time: render and compute everything, but compute the simulation 'clock accordingly'.

To make simulation faster than real-time simulation, several solutions can be tested (but most of the solution require to hack in Blender):

   - hacking at the btDynamicsWorld::stepSimulation() level 
   - hacking the blender clock
   - checking for the 'TimeScale' parameter - http://www.blender.org/documentation/blender_python_api_2_67_1/bpy.types.SceneGameData.html#bpy.types.SceneGameData.use_frame_rate

**Comment by adegroote** [comment]
And finally, after two years, it has been merged in https://git.blender.org/gitweb/gitweb.cgi/blender.git/commit/aae93ae4c6c13e2b30ba272e24354dd020880868, so faster than real-time simulation is a reachable goal for 1.4 \o/

**Comment by severin-lemaignan** [comment]
!!! Congrats!!

**Comment by adegroote** [comment]
Add most of the logic in 02f88ea1a44cb271f2c3553238ae05a2282771d0 and 7c73b3e0cc892d989ed4983eaa202f333bd67686 but was tagged with the bad issue.

**Comment by severin-lemaignan** [comment]
Can we close it?

**Comment by adegroote** [comment]
I will close it when I will push doc update about it. Will work on it after the implementation of #689

**Comment by severin-lemaignan** [comment]
Closed by #689
