### ISSUE TITLE
Adding a DepthCamera crashes MORSE on OSX

### ISSUE THREAD

**Issue by hawesie** [morse-simulator/morse#415]
Over in the [STRANDS project](https://github.com/strands-project/strands_morse) we are happily running a MORSE robot with lots of sensors etc. under ROS on Ubuntu. This mostly works on OSX too, but when I add a DepthCamera to the robot, MORSE crashes. The builder used works fine on Ubuntu, and fine on OSX until the the DepthCamera is added. 

The builder we are using is here: https://github.com/strands-project/strands_morse/blob/master/strands_sim/src/strands_sim/builder/robots/scitosA5.py

If I comment out lines 104 onwards it works fine. If I put lines 104 to 107 (or all the remaining lines) back in, I get a segmentation fault. 

I have placed the output here: https://gist.github.com/hawesie/6066221 including both the MORSE output and the file morse_default_autorun.crash.txt. This is using the latest version of MORSE from GitHub, Blender 2.67 and Python 3.3.0.

Any pointers you can give me as where to start looking for the bug would be gratefully received.

**Comment by adegroote** [comment]
Fixed by e33bfb3157bb7657dd8c9f6dbc2d67fbbeac4f28. Tested with blender-2.73a / python 3.4.2

**Comment by hawesie** [comment]
Exciting, thanks!
