### ISSUE TITLE
Reworking the execution_loop image

### ISSUE THREAD

**Issue by adegroote** [morse-simulator/morse#575]
One with some inkscape skill (so definitively not me :D) should rework the figure showed on 
https://www.openrobots.org/morse/doc/latest/dev/execution_loop.html

The figure misses several informations:
- simulation_main function should appears with 3 (4) substates:
   - datastream_manager action (ok its new)
   - clock update 
   - service management (Morse_service.process_block())
   - optionally multi-node synchronisation

**Comment by adegroote** [comment]
On addition, simulation_main is called at the beginning of the simulation loop, so it should appear at the top of the figure. I don't think it is guaranteed by BGE, through it seems to work reliability on various blender / scene configuration.

**Comment by severin-lemaignan** [comment]
Would this do? (I'll take care of improving the style afterwards)
![simulation_main_loop_overview](https://cloud.githubusercontent.com/assets/385379/7163262/5c27049c-e399-11e4-8711-8a29b252c4e0.png)

**Comment by adegroote** [comment]
MorseServices.process() is in simulation_main() after "services.action()".
clock.update() and services.action() are independent of external software.

Otherwise, good :) Thanks.

**Comment by user597** [comment]
@severin-lemaignan
I liked your schema, with which software you released it ?

**Comment by skadge** [comment]
@adegroote clock update is *always* independent of external world? I believed it could be provided by an external clock...

**Comment by skadge** [comment]
@user597 The source file is there: https://github.com/morse-simulator/morse/blob/master/doc/media/simulation_main_loop_overview.svg
Made with Inkscape a long time ago, and really ugly. I'll try to improve it before the end of the week.

**Comment by adegroote** [comment]
Well, it is possible to have clock synchronization through external source (it is embedded in datastream.action()), but not to say "the time is now xxx". The first one allows to synchronize with other simulators or to run "slower" than real-time : you basically control the 'tick' but not how much time elapsed between each time. The second would be cool and more general purpose, but requires change in BGE (which seems to never happen :D).

I need to update https://www.openrobots.org/morse/doc/latest/dev/time_event.html to describe it.

**Comment by severin-lemaignan** [comment]
@adegroote Here a new version, with refreshed graphics.
![simulation_main_loop_overview](https://cloud.githubusercontent.com/assets/385379/7231033/e59f9bb2-e772-11e4-841f-06fc2194afea.png)

**Comment by adegroote** [comment]
Looks good, through the "right order" in supervision_main is 1 3 4 2 5 :)

Thanks for the work.

**Comment by severin-lemaignan** [comment]
@adegroote Yes, I know, but is there a real reason for that? Because when I was drawing the diagram, it was more logical to me to have the steps in that order (ie, update datastream managers and request managers one after the others, since they are 'similar' object). Anyway, I'll send the PR, I can still fix it if this is important.

**Comment by adegroote** [comment]
If I remember properly, it can have its importance, through I'm not sure I got the logic completely right.
The main issue was the implementation of time.sleep, which is a asynchronous method of the 'virtual service object' time_management (running in 4) (and clock update is done is 3). It is even more fun if you add tick synchronization :). Your proposal is probably OK, but does not match really the code.

**Comment by severin-lemaignan** [comment]
Alright, I've updated the figure the have the correct order + improved a little bit the rendering in the documenation (full width)
