### ISSUE TITLE
[OS X] Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by tiberiusferreira** [morse-simulator/morse#576]
Hello, I know both Morse and Blender need to use the same version of python. So I installed Python 3.4 from this commit at homebrew git:
 git checkout ec660d18c16ba76b3be8c82ac2e8232ac368a233 /usr/local/Library/Formula/python3.rb
 Then I installed morse with:
 brew install morse-simulator --with-ros
 I also changed the morse max version because of https://github.com/morse-simulator/morse/issues/574 to 2.73. Morse check gives: 
- Checking up your environment...
- MORSE has only been tested on Linux. It may work
  on other operating systems as well, but without any guarantee
- Found MORSE libraries in '/usr/local/lib/python3.4/site-packages/morse/blender'. Alright.
- Trying to figure out a prefix from the script location...
- Default scene found. The prefix seems ok. Using it.
- Setting $MORSE_ROOT environment variable to default prefix [/usr/local/]
- Checking version of /Applications/Blender/Blender.app/Contents/MacOS/blender... Found v.2.72.0
- Blender found from $MORSE_BLENDER. Using it (Blender v.2.72.0)
- Checking version of Python within Blender /Applications/Blender/Blender.app/Contents/MacOS/blender... Found v.3.4.0
- Blender and Morse are using Python 3.4.0. Alright.
- Your environment is correctly setup to run MORSE.

but as soo as I try to do anything with it, I get :

A window opens and closes and in the terminal:
- Loading simulation </Users/tiberio/Downloads/0/teste8/run.py>.
- morse UNKNOWN-dirty
- MORSE has only been tested on Linux. It may work
  on other operating systems as well, but without any guarantee

ndof: 3Dx driver not found
found bundled python: /Applications/Blender/Blender.app/Contents/MacOS/../Resources/2.72/python
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

Thanks in advance. 
PS: OS X 10.10 Yosemite Macbook pro retina mid 2012

**Comment by seantrott** [comment]
Sorry to restart this thread, but I'm facing the same issue (after addressing an unrelated issue). When I run "morse check", everything is fine - but actually running a scene causes this "fatal python error" and "abort trap: 6". I installed Blender 2.72b, and changed the max  blender version to 2.73. I was running Morse with python 3.4.

I uninstalled morse and reinstalled it after uninstalling python3 and reinstalling it as python3.4.2 (as suggested). Then I ran "morse check", and the original error persisted: Morse has been compiled for python 3.4.2 but blender is for python 3.4.0. How do I "uncheck" morse version checking? If I do that, will I be able to run the morse scenes?
