### ISSUE TITLE
MORSE 1.2.1 fails in current Debian due to Blender >= 2.72

### ISSUE THREAD

**Issue by severin-lemaignan** [morse-simulator/morse#582]
The MORSE package does not currently work in Debian due to Debian having Blender 2.72 and the lastest MORSE release mandating Blender <= 2.71.

We should quickly do a new (point ?) release otherwise morse is going to be soon removed from the debian archive. 

Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771132

**Comment by severin-lemaignan** [comment]
@adegroote is there any reason for not yet pushing the tag?

**Comment by adegroote** [comment]
Was waiting for debian answer which never happens (but they added the needed patches). Will push it later in this day.

**Comment by adegroote** [comment]
Just pushed the tag and the archive in the right place.
