### ISSUE TITLE
Blender & MORSE Python version matching requirement

### ISSUE THREAD

**Issue by nicolaje** [morse-simulator/morse#584]
At line 300 of the morse script there is a call to check if MORSE and Blender were built with the same Python version:

our_python_version = '.'.join((str(x) for x in sys.version_info[:3]))

Matching the Major & Minor & Micro numbers is a strong constraint as the python version installed on the system doesn't necessarily exactly match the version shipped with Blender.
Moreover, this doesn't check the version of Python MORSE was built with, but the version of the Python interpreter running MORSE.

I've found that cheating on the micro number to match the version installed on the system:

our_python_version = '3.4.X'

doesn't prevent MORSE and PyMorse to run nicely (OSX, Python 3.4.0, Blender Python 3.4.0, System Python 3.4.1).

Is there a reason for the exact version matching?
Could we at least relax the matching constraint on the micro number and issue warnings instead of stopping the execution?

**Comment by adegroote** [comment]
As shown in issue #600, there are incompatible changes between 3.4.X (for X < 3) and 3.4.3, so I think it is definitively not a good idea to remove the check.

**Comment by severin-lemaignan** [comment]
Alright, let's close this issue for now.
