### ISSUE TITLE
Human Bugs 

### ISSUE THREAD

**Issue by TobiasHecht** [morse-simulator/morse#589]
We're working with the human avatar and are experiencing some bugs/issues with it.

- the initial arm and hand positon is quite unnatural
- switching to hand camera (Key x), the camera view seems to be too close the the object. Often i can't even see the hand. Furthermore it's difficult to even see and navigate graspable objects with that camera view. 
- sometimes, the camera view get's stuck in the human body and can't be relocated anymore
- when moving(especially with shift pressed) in hand camera mode, the camera picture seems to stuck in the human's head( parts of the head, such as eyes and eyebrows are visible)
- if the camera is switched from 3rd to 1st person while moving, it gets stuck behind the head
- in some positions, the hand shakes uncontrollable.

Some of those problems seems to appear in the more recent morse versions (we just updated from 0.6 to 1.2)

![initial_human](https://cloud.githubusercontent.com/assets/9480456/5488264/7adbc0a2-86bb-11e4-9fb8-1bf95fbb20c5.jpg)
Screenshot of the initial human adjustment after the simulation is started.

**Comment by severin-lemaignan** [comment]
Hello @TobiasHecht! You've reported the issues a long time ago, and we never thanked you for that! Sorry! I've just proposed a large rewrite of the human avatar (#682) that clean up many things, but also removes the 'interactive First Person Shooter' mode. I'm trying to gauge interest in reviving the feature. So, are you still using it?

**Comment by severin-lemaignan** [comment]
Since #682 has been merged, the interactive mode does not exist anymore, and this bug report is not meaningful anymore.

Closing it for now, but thanks for reporting the issues!
