### ISSUE TITLE
Camera does not render a blender array

### ISSUE THREAD

**Issue by proto3** [morse-simulator/morse#594]
Hello,
When I use the array modifier for an object in my .blend file, the video camera only render the "clones" when the original object of the array is in its field of vision.

I tried for a simple example with an array of cubes and they are not rendered when the first one is not.

**Comment by adegroote** [comment]
Which versions of Blender and Morse do you use ? Can you provide an example showing the issue ? 
Thanks in advance.

**Comment by adegroote** [comment]
Without precision on your issue, we cannot fix it, and I will close the issue. Thanks in advance.

**Comment by adegroote** [comment]
No answer from op so close the issue.
