### ISSUE TITLE
Update install doc

### ISSUE THREAD

**Issue by pierriko** [morse-simulator/morse#598]
To mention that ROS supports requires source, to avoid monthly mail like: 
https://sympa.laas.fr/sympa/arc/morse-users/2015-02/msg00011.html

**Comment by adegroote** [comment]
Is the sentence from installation not sufficient ? 

```
If you plan to use the simulator with raw sockets or text files as interface (for instance, to integrate MORSE with MatLab or other specific applications), you don’t need anything else, and you can jump to MORSE’s Quickstart. Otherwise, you need to install the software for the desired middlewares
```

**Comment by pierriko** [comment]
regarding the number of ros-support related emails, I'd say no ;-)

**Comment by pierriko** [comment]
hopefully https://github.com/morse-simulator/morse/commit/8f330a75099cf37227ea4b1ee4b9ab2c15e83c00 will help
