### ISSUE TITLE
cmake requiers python 3.2

### ISSUE THREAD

**Issue by pierriko** [morse-simulator/morse#602]
```cmake
set(PythonInterp_FIND_VERSION 3.2)
```
https://github.com/morse-simulator/morse/blob/master/CMakeLists.txt#L29

Why not just 3 ?

**Comment by adegroote** [comment]
Because, as far as I remember, blender never ships version < 3.2. I'm not even sure the code works with python 3.2 nowadays, and I tend to vote to set limitation to python >= 3.3 and blender >= 2.65.

**Comment by adegroote** [comment]
Close this one. Discussion about requirement on morse-dev@
