### ISSUE TITLE
Pocolibs issues in some components

### ISSUE THREAD

**Issue by lesire** [morse-simulator/morse#604]
Viam and Stereopixel components still use the old Pocolibs+AbstractDatastream class instead of PocolibsDataStream and PocolibsDataStreamOutput classes.

Results in:
[helpers.loading] Module not found: cannot import name 'Pocolibs'
[helpers.loading] Could not load the class ViamPoster in morse.middleware.pocolibs.sensors.viam
[helpers.loading] Could not create an instance of morse.middleware.pocolibs.sensors.viam.ViamPoster

I can try to make a hack, but as I am not a Pocolibs user, would be better to be nicely fixed by a Pocolibs user :)

**Comment by adegroote** [comment]
Do you have BUILD_POCOLIBS_VIAM_SUPPORT enabled in Morse (or viam option in robotpkg) ?

**Comment by lesire** [comment]
Yes. Viam is installed, the problem comes from the MORSE viam python 
support who cannot work (uses Pocolibs class which does not exist anymore)

**Comment by adegroote** [comment]
Which version of Morse do you use ? 5dc6c545c9abe040cd6cee9a401a3c2fe33ca95c should have fixed it (but only in master branch).

**Comment by lesire** [comment]
Argh... I have installed robotpkg version...

**Comment by adegroote** [comment]
Close it, as it is fixed in master.
