### ISSUE TITLE
CMake warning: dependency hla/omt.py of 'copy_doc' does not exist

### ISSUE THREAD

**Issue by severin-lemaignan** [morse-simulator/morse#620]
Doing a clean install of the current trunk, CMake gives the following warning (knowing that I did not enabled any middleware in CMake):

```
CMake Warning (dev) at CMakeLists.txt:219 (ADD_DEPENDENCIES):
   Policy CMP0046 is not set: Error on non-existent dependency in
   add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
   Use the cmake_policy command to set the policy and suppress this warning.

   The dependency target "/home/skadge/src/morse/build/fakeenv/hla/omt.py" of
   target "copy_doc" does not exist.
 This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by adegroote** [comment]
Which version of cmake ? How do you call it ? Don't have this issue on 2.8.12.2 with cmake ../.

**Comment by severin-lemaignan** [comment]
Tested on Debian Jessie (ie `cmake-3.0.2`): this may well be the reason!

**Comment by adegroote** [comment]
Can you check it really improve thing on 3.0.2. Works properly on 2.8.12.2.

**Comment by severin-lemaignan** [comment]
This fixes the issue for me. You can merge it. Thank you!
