### ISSUE TITLE
Add a tool to view / dump image from a socket datastream

### ISSUE THREAD

**Issue by adegroote** [morse-simulator/morse#628]
It is a recurrent requirement.

See #625

**Comment by pierriko** [comment]
I can do something from:
https://github.com/morse-simulator/morse/blob/master/testing/base/video_camera_testing.py

**Comment by adegroote** [comment]
Yes. Ideally, it would be nice to put the buffer -> ppm stuff in an helper file, and use it for the test and the tool. While here, we may add a 'text' ('file' would be a better name) backend for video_camera :)
