### ISSUE TITLE
Pioner3DX and PatrolBot make a random rotation before moving forward

### ISSUE THREAD

**Issue by kellymorse** [morse-simulator/morse#637]
Hello,
I am new in morse, and I am using it with ros interface, I am having issues with two robots (Pioner3DX and PatrolBot) when trying to move them forward, backward, left or right, each of them makes a very fast and random rotation (in many times it is around 90deg.) when receiving the first command (the same behaviour with and without ros interface), witch is very annoying for my SLAM algorithm.
I am using morse 1.2 with ubuntu 12.04 and Groovy ros
Any help, please, will be appreciated.
My .py file is bellow:

1- keyboard control:
from morse.builder import *
##################### ROBOT  ####################
p3dx0 =   Pioneer3DX()#PatrolBot()
p3dx0.translate(x=-38.0, y=38.0, z=0.0)
##odometry
odom0 = Odometry()
...
##laser 
scan = Sick()
...
##################### CONTROL  ####################
keyboard = Keyboard()
keyboard.properties(Speed=1.0)
p3dx0.append(keyboard)
##################### ENV.  ####################
env = Environment('/myhomeDIR/envs/maze', fastmode=False)
env.place_camera([0, 0, 60])
env.aim_camera([0, 0, 0])

2- ros topic control
motion = MotionVWDiff()
motion.add_interface('ros',topic='/cmd_vel')
p3dx0.append(motion)

**Comment by adegroote** [comment]
Can you provide a complete and minimal builder script exhibiting the issue ?
Can you try with 1.3 ?

It is strange that you can move at all the robot using your keyboard setup, you  need at least

```
keyboard.properties(ControlType = 'Differential')
```

to make it working properly.

Can you try to launch the pionner3dx_testing.py test (in MORSE/testing/robots/pionner3dx/) ?

**Comment by kellymorse** [comment]
thank you for the help,
I am using morse 1.2, never tried 1.3

adding this line "keyboard.properties(ControlType = 'Differential')"
does not help, I am getting the same behavior!

Yes I am able to launch pionner3dx_testing.py but can't move the robot!?



On Thu, Jul 9, 2015 at 11:24 AM, Arnaud Degroote <notifications@github.com>
wrote:

> Can you provide a complete and minimal builder script exhibiting the issue
> ?
> Can you try with 1.3 ?
>
> It is strange that you can move at all the robot using your keyboard
> setup, you need at least
>
> keyboard.properties(ControlType = 'Differential')
>
> to make it working properly.
>
> Can you try to launch the pionner3dx_testing.py test (in
> MORSE/testing/robots/pionner3dx/) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/morse-simulator/morse/issues/637#issuecomment-119886401>
> .
>



-- 
Khelifa Baizid,
