### ISSUE TITLE
ROS middleware use some outdated / inexistant messages 

### ISSUE THREAD

**Issue by adegroote** [morse-simulator/morse#645]
The doc generation reveals that the following messages does not exist anymore in Indigo

- asctec_msgs
- motion_control_msgs

It will be nice to provide an alternative 'modern' implementation for this types, and a way to use the old type for old ROS release, and new types for 'modern' ROS release.

**Comment by flixr** [comment]
At least the asctec_msgs were never part of the "default" ros messages.
I just included it for one of the rotorcraft actuators since apparently quite a few people were using it and I was asked to add it...
Never used those myself.
