### ISSUE TITLE
Noise in accelerometer

### ISSUE THREAD

**Issue by minotaur-0** [morse-simulator/morse#649]
Hi
I'm reading the code of the accelerometre. but I didn't found where the noise is introduced. 
Is it simulated ?
https://github.com/morse-simulator/morse/blob/master/src/morse/sensors/accelerometer.py

**Comment by adegroote** [comment]
In Morse design, noise are not implemented in sensors directly, but in a separate layer called modifiers. Depending what kind of noise you need, you can looks in Morse.modifiers if something feet your need. 


-------- Message d'origine --------
De : Minotaur <notifications@github.com>
Envoyé : 16 août 2015 12:33:00 HAEC
À : morse-simulator/morse <morse@noreply.github.com>
Objet : [morse] Noise in accelerometer (#649)

Hi
I'm reading the code of the accelerometre. but I didn't found where the noise is introduced. 
Is it simulated ?
https://github.com/morse-simulator/morse/blob/master/src/morse/sensors/accelerometer.py

---
Reply to this email directly or view it on GitHub:
https://github.com/morse-simulator/morse/issues/649
-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by adegroote** [comment]
Can I close it ?
