### ISSUE TITLE
Update our travis stuff to use trusty

### ISSUE THREAD

**Issue by adegroote** [morse-simulator/morse#668]
Travis is Opening up the Ubuntu Trusty beta <http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/> as of yesterday. 

It should simplify a lot our travis infrastructure to use the trusty system and should be more realistic target than 12.04 nowadays.

**Comment by severin-lemaignan** [comment]
In that regard, I quote a useful comment by @wjwwood:

> @Mani, if you look at my PR, that's why I used language: generic, which uses their minimal image 
> and does not use a non-system Python.
>
> The issue you're running into is that the Python that is turned on by default is a non-system Python 
> 2.6 install which is unaffected by installing Python packages with apt-get. By using the minimal image 
> you avoid having to deal with custom versions of Python.
