### ISSUE TITLE
Cannot build version 1.4

### ISSUE THREAD

**Issue by andystevens91** [morse-simulator/morse#701]
Hi!
I just started using MORSE today. I'm trying to get a working installation of MORSE 1.4 in order to use [morseweb](https://github.com/yarox/morseweb), but, no matter how I install it, I always get v1.2.
I tried:

1. installing using `apt-get install morse-simulator` --> `morse -v` 1.2
2. building from git branch master  --> `morse -v` 1.2
3. building from git branch 1.4_STABLE  --> `morse -v` 1.2
4. downloading the tarball of 1.4 and building from there  --> `morse -v` 1.2

After every try I've nuked the installation and tried a different method, but `morse -v` is ALWAYS 1.2.
What am I doing wrong?

**Comment by adegroote** [comment]
On 11/Mar - 13:05, Andrea Di Stefano wrote:
> Hi!
> I just started using MORSE today. I'm trying to get a working installation of MORSE 1.4 in order to use [morseweb](https://github.com/yarox/morseweb), but, no matter how I install it, I always get v1.2.
> I tried:
> 
> 1. installing using `apt-get install morse-simulator` --> `morse -v` 1.2
> 2. building from git branch master  --> `morse -v` 1.2
> 3. building from git branch 1.4_STABLE  --> `morse -v` 1.2
> 4. downloading the tarball of 1.4 and building from there  --> `morse -v` 1.2
> 
> After every try I've nuked the installation and tried a different method, but `morse -v` is ALWAYS 1.2.
> What am I doing wrong?
> 
Do you remove the morse-simulation debian package ? I guess you still
get the Morse version installed in /usr/bin from the debian package.

**Comment by andystevens91** [comment]
Yep, with `apt-get --purge remove morse-simulator`

**Comment by adegroote** [comment]
In which prefix do you install Morse? what returns the command 

which morse

**Comment by andystevens91** [comment]
`/usr/local/bin/morse`, which I think is the default prefix for the cmake installation.

**Comment by pierriko** [comment]
you can check if `${PREFIX}/lib/python3*/*-packages/morse/version.py` is correct

**Comment by andystevens91** [comment]
Sorry, I have been busy this week and did not check for new replies.
In the end I did it by building from the 1.4 tarball AFTER formatting the disk and reinstalling the OS, so I suppose there was still something left from the previous installations.
Thanks for your help everyone!
