### ISSUE TITLE
Documentation little issues 

### ISSUE THREAD

**Issue by sept64** [morse-simulator/morse#742]
Hi morse dev team ! 

Don't know if this is the right place to post that (if not I'm sorry) but there are two very little issues in the wiki at this page : https://www.openrobots.org/morse/doc/latest/dev/adding_modifier.html#id1

In the example of the modifier : pamateter should be parameter

And in the last lines :  "Last, if you want to use it more easily, you can add some entries in morse.builder.data.MORSE_DATASTREAM_DICT." should be "Last, if you want to use it more easily, you can add some entries in morse.builder.data.MORSE_MODIFIER_DICT" (because MORSE_DATASTREAM_DICT don't deals with modifiers but with datastream stuff). 

Hope it helps, 
T.

**Comment by pierriko** [comment]
Thanks for the proofreading :+1: 
We'll update soon.
Meanwhile, feel free to open pull-request / send patch, there is already a bit off cleaning needed and some on the way, see https://github.com/morse-simulator/morse/pulls
