### ISSUE TITLE
MOOS new python interface

### ISSUE THREAD

**Issue by msis** [morse-simulator/morse#752]
What is the best practice to update a middleware?

`MOOS` has now an official interface for [python](https://github.com/themoos/python-moos) and I want to contribute with a new interface to MORSE, but afraid if I replace the existing one by @davidhodo through a PR, it might ruin legacy code.

Should we have a `MOOS2` (or even `MOOSv10` as the creator likes to call it) interface in this case?

**Comment by severin-lemaignan** [comment]
@msis Great to know that MOOS is still used!
What kind of breakages do you expect? would this change fundamentally how MORSE interact with MOOS?

I let  @davidhodo comment, but if the current user base for MOOS is small (as I suspect), then I would favour just replacing the current implementation with the official `moos-python` bindings. Carrying over legacy code is not really my cup of tea unless we have solid reasons to do so.

**Comment by msis** [comment]
In `MOOSv10`, asynchronous communication with the `MOOSDB` which allows having callbacks for different messages in addition to the traditional way of getting mail implemented here.

I will be replacing the docs too all along.

**Comment by davidhodo** [comment]
I am no longer using MOOS with Morse.  I'm not sure anyone is maintaining
the pyMOOS bindings either.  I think replacing the current implementation
with something MOOSv10 compatible is the way to go.

David

**Comment by severin-lemaignan** [comment]
Ok, thanks @davidhodo  for the feedback.
@msis please go ahead with a PR, then!

**Comment by msis** [comment]
Hi guys!
I finally had some time to finish the migration and create the PR #757 .
