### ISSUE TITLE
ROS middleware installation notes mistake

### ISSUE THREAD

**Issue by guilhembn** [morse-simulator/morse#769]
On this piece of documentation : [ROS Installation Notes](http://www.openrobots.org/morse/doc/1.3/user/installation/mw/ros.html) in order to install pyYAML, rospkg and catkin for Python3 it is suggested to execute `sudo python3 setup.py install`.
According to this [SO topic](https://stackoverflow.com/questions/18199853/error-could-not-create-library-python-2-7-site-packages-xlrd-permission-den), `sudo` must not be used to install with python. Furthermore, I had errors installing the packages using `sudo` : `error: could not create 'src/catkin_pkg.egg-info': Permission denied` while everything works fine using `python3 setup.py install --user`.
The documentation may need to be fixed.

**Comment by nicolaje** [comment]
Hello,

note that I find it way easier to just run:

pip3 install catkin_pkg rospkg pyyaml

Regards,

Jeremy

2017-10-10 9:25 GMT+02:00 Guilhem B. <notifications@github.com>:

**Comment by severin-lemaignan** [comment]
Fixed using @nicolaje  suggestion. Thanks.
