### ISSUE TITLE
Change logger level of ROS middleware to INFO (or default)

### ISSUE THREAD

**Issue by CodeFinder2** [morse-simulator/morse#771]
Hi,

I would suggest to change the logger level (see code [here](https://github.com/morse-simulator/morse/blob/master/src/morse/middleware/ros/abstract_ros.py#L52)) to `rospy.INFO` or simply omit that parameter to use the ROS default. This causes various outputs during the startup of MORSE which renders the logging somehow unusable (too many lines). IMHO; `rospy.DEBUG` should only be used during development (of MORSE).

Any comments on this?

Thanks!

**Comment by dgerod** [comment]
It's OK for me, I think that best solution is to omit the parameter so we will do what is default for ROS. I have just checked how to manage [vervosity](http://wiki.ros.org/Verbosity%20Levels) in ROS, and it match what you are proposing.

**Comment by CodeFinder2** [comment]
Thanks for your reply, done (see https://github.com/morse-simulator/morse/pull/775 ).
