### ISSUE TITLE
something wrong with builder introspection ?

### ISSUE THREAD

**Issue by pierriko** [morse-simulator/morse#786]
Creating any function or class in a morse builder script fails to run with:

```
Blender Game Engine Started
Python module can't be imported - object 'atrv', controller 'Python':
[ERROR][MORSE] Uncaught exception, quit Blender.
ImportError: No module named 'calling'
ImportError: No module named 'calling'
```

Take any simulation builder script and add:

```
def toto():
  pass
```

you will get this issue.

My setup is: Fedora 26, Blender 2.79 tar.gz from d.b.o
export MORSE_SILENT_PYTHON_CHECK=1
export MORSE_POP_PYTHONLIB=/usr/lib64/python3.6

**Comment by severin-lemaignan** [comment]
A bit of backtrace would be useful, if possible...

**Comment by pierriko** [comment]
```python
env.create()
```
soles this issue
